### PR TITLE
Test via scripts/gitbook-serve. Add a .gitignore

### PR DESCRIPTION
**Pull request by nealmcb**

### CODE REVIEW

**Comment by ruimarinho** [comment]
Can you split the changes into two separate commits?

**Comment by ruimarinho** [comment]
Can you split the changes into two separate commits?

**Comment by nealmcb** [comment]
Sorry, but it's time for me to get back to paid work!!
And not clear it's worth the benefit just to give us each some extra hassle, though I do appreciate the notion of clarity in the git history.

**Comment by nealmcb** [comment]
Thanks for making these changes in 6ff3777!

**Pull request closed without merging**
